import axios, { AxiosInstance, AxiosError } from 'axios';
import { env } from '../config/env';
import { SessionStatus } from '../types';

// ============================================================
// WAHA Service
// All HTTP communication with the WAHA Docker container.
// Engine: NOWEB (no Puppeteer — pure WhatsApp Web protocol)
// chatId format for phone numbers: "<number>@c.us"
// ============================================================

const wahaClient: AxiosInstance = axios.create({
  baseURL: env.WAHA_BASE_URL,
  headers: {
    'X-Api-Key': env.WAHA_API_KEY,
    'Content-Type': 'application/json',
  },
  timeout: 15_000, // 15s — WAHA can be slow during session startup
});

// ============================================================
// Typed WAHA response shapes
// ============================================================

export interface WahaSessionInfo {
  name:   string;
  status: SessionStatus;
  me?: {
    id:       string; // e.g. "201012345678@c.us"
    pushName: string;
  };
}

export interface WahaQRResult {
  /** Raw base64 data (no data URI prefix) from WAHA */
  value: string;
  /** Fully qualified data URI returned by getQR */
  dataUri: string;
}

/** Sentinel value — QR hasn't been generated by WAHA yet */
export const QR_NOT_READY = 'QR_NOT_READY' as const;

// ============================================================
// Helper: format phone number as WhatsApp chatId
// Input:  "201012345678"       → "201012345678@c.us"
// Input:  "201012345678@c.us"  → unchanged
// ============================================================
function toChatId(phone: string): string {
  const cleaned = phone.replace(/[^\d]/g, '');
  return cleaned.endsWith('@c.us') ? cleaned : `${cleaned}@c.us`;
}

// ============================================================
// Helper: extract meaningful error text from WAHA responses
// ============================================================
export function extractWahaError(err: unknown): string {
  if (err instanceof AxiosError) {
    const detail =
      (err.response?.data as { message?: string; error?: string })?.message ??
      (err.response?.data as { message?: string; error?: string })?.error ??
      err.message;
    return detail;
  }
  return String(err);
}

// ============================================================
// Session Management
// ============================================================

/**
 * Create and start a new WAHA session.
 * Session lifecycle: STOPPED → STARTING → SCAN_QR_CODE → CONNECTED
 */
export async function startSession(sessionName: string): Promise<WahaSessionInfo> {
  try {
    const { data } = await wahaClient.post<WahaSessionInfo>('/api/sessions', {
      name:   sessionName,
      config: { webhooks: [] },
    });
    return data;
  } catch (err) {
    throw new Error(`WAHA startSession failed: ${extractWahaError(err)}`);
  }
}

/**
 * Get live status of a single WAHA session.
 * Includes `me` object when CONNECTED (has phone number / push name).
 */
export async function getSession(sessionName: string): Promise<WahaSessionInfo> {
  try {
    const { data } = await wahaClient.get<WahaSessionInfo>(
      `/api/sessions/${sessionName}`
    );
    return data;
  } catch (err) {
    throw new Error(`WAHA getSession failed: ${extractWahaError(err)}`);
  }
}

/**
 * List all sessions visible to this WAHA instance.
 */
export async function getAllSessions(): Promise<WahaSessionInfo[]> {
  try {
    const { data } = await wahaClient.get<WahaSessionInfo[]>('/api/sessions');
    return data;
  } catch (err) {
    throw new Error(`WAHA getAllSessions failed: ${extractWahaError(err)}`);
  }
}

/**
 * Get QR code for a session waiting to be scanned.
 * Returns WahaQRResult if the QR is ready, or the QR_NOT_READY sentinel
 * if WAHA hasn't generated the QR yet (session is still STARTING).
 */
export async function getQR(
  sessionName: string
): Promise<WahaQRResult | typeof QR_NOT_READY> {
  try {
    const { data } = await wahaClient.get<{ value: string } | string>(
      `/api/${sessionName}/auth/qr?format=image`
    );

    // WAHA can return either an object { value: "base64..." } or a raw base64 string
    let raw: string;
    if (typeof data === 'string') {
      raw = data;
    } else if (typeof data === 'object' && data !== null && 'value' in data) {
      raw = (data as { value: string }).value;
    } else {
      return QR_NOT_READY;
    }

    if (!raw || raw.trim() === '') return QR_NOT_READY;

    // Ensure it has a data URI prefix for frontend consumption
    const dataUri = raw.startsWith('data:')
      ? raw
      : `data:image/png;base64,${raw}`;

    return { value: raw, dataUri };
  } catch (err) {
    if (err instanceof AxiosError) {
      const status = err.response?.status;
      // 404 / 422 = QR not generated yet — session is still initializing
      if (status === 404 || status === 422 || status === 400) {
        return QR_NOT_READY;
      }
    }
    throw new Error(`WAHA getQR failed: ${extractWahaError(err)}`);
  }
}

/**
 * Stop and remove a session from WAHA.
 * Best-effort — caller should handle errors gracefully.
 */
export async function stopSession(sessionName: string): Promise<void> {
  try {
    await wahaClient.delete(`/api/sessions/${sessionName}`);
  } catch (err) {
    throw new Error(`WAHA stopSession failed: ${extractWahaError(err)}`);
  }
}

// ============================================================
// Message Sending
// ============================================================

/** Send a plain text message */
export async function sendText(
  session: string,
  to: string,
  text: string
): Promise<{ id: string }> {
  try {
    const { data } = await wahaClient.post<{ id: string }>('/api/sendText', {
      session,
      chatId: toChatId(to),
      text,
    });
    return data;
  } catch (err) {
    throw new Error(`WAHA sendText failed: ${extractWahaError(err)}`);
  }
}

/** Send an image message with optional caption */
export async function sendImage(
  session: string,
  to: string,
  url: string,
  caption?: string
): Promise<{ id: string }> {
  try {
    const { data } = await wahaClient.post<{ id: string }>('/api/sendImage', {
      session,
      chatId: toChatId(to),
      file:    { url },
      caption: caption ?? '',
    });
    return data;
  } catch (err) {
    throw new Error(`WAHA sendImage failed: ${extractWahaError(err)}`);
  }
}

/** Send a video message with optional caption */
export async function sendVideo(
  session: string,
  to: string,
  url: string,
  caption?: string
): Promise<{ id: string }> {
  try {
    const { data } = await wahaClient.post<{ id: string }>('/api/sendVideo', {
      session,
      chatId: toChatId(to),
      file:    { url },
      caption: caption ?? '',
    });
    return data;
  } catch (err) {
    throw new Error(`WAHA sendVideo failed: ${extractWahaError(err)}`);
  }
}

/** Send an audio/voice message */
export async function sendAudio(
  session: string,
  to: string,
  url: string
): Promise<{ id: string }> {
  try {
    const { data } = await wahaClient.post<{ id: string }>('/api/sendVoice', {
      session,
      chatId: toChatId(to),
      file:   { url },
    });
    return data;
  } catch (err) {
    throw new Error(`WAHA sendAudio failed: ${extractWahaError(err)}`);
  }
}

/** Send a document/file with optional caption */
export async function sendFile(
  session: string,
  to: string,
  url: string,
  caption?: string
): Promise<{ id: string }> {
  try {
    const { data } = await wahaClient.post<{ id: string }>('/api/sendFile', {
      session,
      chatId: toChatId(to),
      file:    { url },
      caption: caption ?? '',
    });
    return data;
  } catch (err) {
    throw new Error(`WAHA sendFile failed: ${extractWahaError(err)}`);
  }
}

/** Send a location pin */
export async function sendLocation(
  session: string,
  to: string,
  latitude: number,
  longitude: number,
  title?: string
): Promise<{ id: string }> {
  try {
    const { data } = await wahaClient.post<{ id: string }>('/api/sendLocation', {
      session,
      chatId: toChatId(to),
      latitude,
      longitude,
      title:  title ?? '',
    });
    return data;
  } catch (err) {
    throw new Error(`WAHA sendLocation failed: ${extractWahaError(err)}`);
  }
}
